### ISSUE TITLE
Roadmap towards a printable version 

### ISSUE THREAD

**Issue by mli** [zackchase/mxnet-the-straight-dope#317]
The goal is to get a printing quality version within 4 weeks. The major steps include

- [ ] Select a subset of notebooks to publish (because unlikely we can get all done before that time)
- [ ] Merge the changes (mostly code changes) made in the Chinese version
- [ ] Setup the new CI pipeline which evaluates every notebook (which already exists in the Chinese version)
- [ ] Build a printable PDF version during the CI (also already exists in the Chinese version)
- [ ] Optional, use markdown format to store the notebook to make code merging easier. But we will publish a `ipynb` version as well.

**Comment by sebg** [comment]
Achieving this issue (specifically getting to a printable PDF) will fix issues https://github.com/zackchase/mxnet-the-straight-dope/issues/215 and https://github.com/zackchase/mxnet-the-straight-dope/issues/236

**Comment by alanchua** [comment]
Hi, I just happen to to come across this discussion, is a PDF of the English version available somewhere just like the Chinese version? 

The content of the book is great btw. 😀

**Comment by zackchase** [comment]
@mli - let's get a provisional PDF available soon - even if it's not perfect. let's aim for 2-4 weeks to have a beta PDF build?

**Comment by zackchase** [comment]
@alanchua - thanks man! glad you like it

**Comment by alanchua** [comment]
@zackchase. Really appreciate the response!
